spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 43108c699dacc365b4b86b932e6c7b60
            client-secret: R7zG5IXGFlxTYPowDVQmBwMJHcE0OyJu

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop

ourlunch:
  url: http://localhost:8080/
