
### 개발용 사용자 로그인 API

POST http://localhost:8080/admin/login
Content-Type: application/json


### 팸생성 API

POST http://localhost:8080/dev/api/v1/initialization
Content-Type: application/json

{
  "userName": "우점",
  "appetite": "아재입맛",
  "companyName": "우점주식회사",
  "familyName": "우점팸"
}


### 사용자 프로필 조회 API

GET http://localhost:8080/dev/api/v1/member/profile
Content-Type: application/json


### 팸 멤버 목록 조회 API

GET http://localhost:8080/dev/api/v1/family/1/members
Content-Type: application/json

###

GET http://localhost:8080/family/join/921C511097F1466BA7F0201F35DFCEF2
Content-Type: application/json

###